name: package
on:
  push:
    tags:        
      - "*"
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: 01 Checkout Code
      uses: actions/checkout@v3
    - name: 02 Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100
    - name: 03 Restore Dotnet Tool
      run: dotnet tool restore
    - name: 04 Check Code Format
      run: dotnet format --verify-no-changes 
    - name: 05 Build with dotnet
      run: dotnet build
    - name: 06 Count Test Projects
      run: echo TEST_PROJ_COUNT=$(ls -l test |grep "^d"|wc -l) >> $GITHUB_ENV
    - name: 07 Run Unit test
      if: env.TEST_PROJ_COUNT>0
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*Test]*"
    - name: 11 Set Git Tag Name
      run: echo GIT_TAG=${GITHUB_REF:10} >> $GITHUB_ENV
    - name: 12 Set Pack Version
      run: echo PACK_VERSION=${GIT_TAG#v} >> $GITHUB_ENV
    - name: 13 Create Package
      run: dotnet pack -p:PackageVersion=${PACK_VERSION} -p:RepositoryUrl=${{github.event.repository.url}} -p:PackageProjectUrl=${{github.event.repository.url}} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o .publish --configuration Release
    - name: 14 Push Package
      run: bash ./.github/scripts/pushpack.sh .publish ${{secrets.NUGET_APIKEY}}

